services:
  - type: web
    name: snapvault
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
